### ISSUE TITLE
InvalidCharacterError: String contains an invalid character

### ISSUE THREAD

**Issue by ArielSaldana** [mixpanel/webcomponent#2]
Error happens in Firefox.

<img width="458" alt="screen shot 2017-04-26 at 3 29 13 pm" src="https://cloud.githubusercontent.com/assets/7002530/25452955/5cb52002-2a95-11e7-8c44-6df379048a14.png">

**Comment by tdumitrescu** [comment]
This isn't quite enough info to go on. Can you provide an example that reproduces your issue? And info about Firefox version and OS version? What is the name of the element you're trying to register (probably the best clue to why it's complaining about an illegal character)?

Also, are you using a Custom Elements polyfill? Firefox does not have native support for v1 custom elements yet, and v0 custom elements must be enabled by the user with a feature flag (`dom.webcomponents.enabled`). So for Firefox with the current (v1) version, you'll want to include a script like https://github.com/webcomponents/custom-elements.

**Comment by tdumitrescu** [comment]
Without any further data to go on, I'm going to close this as likely an attempt to register an illegal element name (e.g., `customElements.define('<my-element>')` rather than `customElements.define('my-element')`). If that's not the case and we can reproduce the issue, please feel free to reopen.
